import Head from "next/head";
import Home from "../layouts/Home";
import { client } from "lib/client";
import Product from "components/elements/common/Product";
import { HeroSection, MissionSection } from "components/home";

export default function index({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <HeroSection /> */}
        <MissionSection products={products} />
      </main>
    </>
  );
}

index.layout = Home;

export const getServerSideProps = async () => {
  const query = `*[_type == "product"]`;
  const products = await client.fetch(query);

  return {
    props: {
      products
    }
  };
};
