import Head from "next/head";
import Home from "../layouts/Home";

export default function index() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1 className="text-red-500 text-3xl">Welcome</h1>
		</>
	);
}

index.layout = Home;
